# Generated by Django 4.1.3 on 2022-12-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_customuser_options_alter_customuser_managers_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="identifier",
            new_name="username",
        ),
    ]
