# Generated by Django 4.1.3 on 2022-12-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_followrequest_followrequest_unique_requests"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="followrequest",
            name="unique_requests",
        ),
        migrations.RenameField(
            model_name="followrequest",
            old_name="recipient_id",
            new_name="recipient",
        ),
        migrations.RenameField(
            model_name="followrequest",
            old_name="sender_id",
            new_name="sender",
        ),
        migrations.AddConstraint(
            model_name="followrequest",
            constraint=models.UniqueConstraint(
                fields=("sender", "recipient"), name="unique_requests"
            ),
        ),
    ]
