# Generated by Django 4.1.3 on 2022-12-04 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author_id",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="photo_id",
            new_name="photo",
        ),
        migrations.RenameField(
            model_name="like",
            old_name="photo_id",
            new_name="photo",
        ),
        migrations.RenameField(
            model_name="photo",
            old_name="owner_id",
            new_name="owner",
        ),
    ]
