# Generated by Django 4.1.3 on 2022-12-04 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_rename_author_id_comment_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="fan_id",
            new_name="fan",
        ),
    ]
