# Generated by Django 4.1.3 on 2022-12-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0003_rename_fan_id_like_fan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to="images/%Y/%m/%d/"),
        ),
    ]
